authors:
  - name: Sigrún Helga Lund
    email: sigrunhl@hi.is
  - name: Anna Helga Jónsdóttir
    email: ahj@hi.is
  - name: Bjarki Þór Elvarson
    email: bjarki.elvarsson@hafogvatn.is
description: R frá grunni
name: R_fra_grunni
