authors:
  - name: Valentina Giangreco M Puletti
    email: vgmp@hi.is
  - name: Hulda Hvönn Kristinsdóttir
    email: hhk6@hi.is
author: Valentina Giangreco M Puletti
description: Hagnýt stærðfræðigreining (STÆ105G)
name: stae105g
email: vgmp@hi.is