name: Issue
on:
  issue_comment:
    types: [created]
jobs:
  issue:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        id: debug
        run: |
          title="Ný athugasemd"
          color=2061822
          payload=$(cat <<EOF
          {
            "content": "$title",
            "avatar_url": "https://www.shareicon.net/data/128x128/2015/08/28/92005_social-media_512x512.png",
            "embeds": [
              {
                "title": "${{ github.event.issue.title }}",
                "description": "${{ github.event.comment.body }}",
                "url": "${{ github.event.comment.html_url }}",
                "color": $color,
                "author": {
                  "name": "${{ github.event.comment.user.login}}",
                  "url": "${{ github.event.comment.user.url}}",
                  "icon_url": "${{ github.event.comment.user.avatar_url}}"
                }
              }
            ]
          }
          EOF
          )
          echo ::set-output name=discord_payload::"'"$payload"'"
      - name: Notify
        run: |
          set -x
          echo ${{ steps.debug.outputs.discord_payload }}
          ./test.sh  \
            -w ${{ secrets.DISCORD_WEBHOOK }} \
            -c ${{ steps.debug.outputs.discord_payload }}
