name: Issue
on:
  issues:
    types: [opened, closed]
jobs:
  issue:
    name: Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        id: debug
        run: |
          if [ ${{ github.event.action }} = "opened" ]; then
            title="Nýtt mál opnað 🙀"
            color=16711680
          elif [ ${{ github.event.action }} = "closed" ]; then
            title="Máli var lokað 🥳"
            color=32768
          fi
          payload=$(cat <<EOF
          {
            "content": "$title",
            "avatar_url": "https://www.shareicon.net/data/128x128/2015/08/28/92005_social-media_512x512.png",
            "embeds": [
              {
                "title": "${{ github.event.issue.title }}",
                "description": "${{ github.event.issue.body }}",
                "url": "${{ github.event.issue.url }}",
                "color": $color,
                "author": {
                  "name": "${{ github.event.issue.user.login}}",
                  "url": "${{ github.event.issue.user.url}}",
                  "icon_url": "${{ github.event.issue.user.avatar_url}}"
                }
              }
            ]
          }
          EOF
          )
          echo ::set-output name=discord_payload::"'"$payload"'"
      - name: Notify
        run: |
          set -x
          echo ${{ steps.debug.outputs.discord_payload }}
          ./test.sh  \
            -w ${{ secrets.DISCORD_WEBHOOK }} \
            -c ${{ steps.debug.outputs.discord_payload }}
